services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    command: go run /usr/src/app/cmd/api/api.go
    build:
      context: .
    develop:
      watch:
      - action: sync+restart
        target: /usr/src/app
        path: ./
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/example?schema=public
    depends_on:
      - postgres

volumes:
  postgres-data: